// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACIxlEDr0htuGqeTWtsrekadIcuH_BAvE',
    appId: '1:45363654707:web:626e87507501506d8a7346',
    messagingSenderId: '45363654707',
    projectId: 'employeeapp-baa80',
    authDomain: 'employeeapp-baa80.firebaseapp.com',
    storageBucket: 'employeeapp-baa80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfw2ZobszmUoQHoEcKIE8fmid8IXD7Yaw',
    appId: '1:45363654707:android:4d363533ea2227358a7346',
    messagingSenderId: '45363654707',
    projectId: 'employeeapp-baa80',
    storageBucket: 'employeeapp-baa80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-moghkbHvCgyOQ3_DuZJhmwKjq2i0UzQ',
    appId: '1:45363654707:ios:a31e0bb536dbb3bc8a7346',
    messagingSenderId: '45363654707',
    projectId: 'employeeapp-baa80',
    storageBucket: 'employeeapp-baa80.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-moghkbHvCgyOQ3_DuZJhmwKjq2i0UzQ',
    appId: '1:45363654707:ios:a31e0bb536dbb3bc8a7346',
    messagingSenderId: '45363654707',
    projectId: 'employeeapp-baa80',
    storageBucket: 'employeeapp-baa80.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACIxlEDr0htuGqeTWtsrekadIcuH_BAvE',
    appId: '1:45363654707:web:fac04c1b102751a08a7346',
    messagingSenderId: '45363654707',
    projectId: 'employeeapp-baa80',
    authDomain: 'employeeapp-baa80.firebaseapp.com',
    storageBucket: 'employeeapp-baa80.firebasestorage.app',
  );
}
